### ISSUE TITLE
"Other Queries" not accepted as query group

### ISSUE THREAD

**Issue by FrankFromGermany** [nolockcz/PowerPlatform#1]
I receive an error message when importing json file:

"Imported file does not have a json structure.
...
'pbi:mashup.   ...   .queryGroupId', line 1, ...
..."

Relevant json part:
"FactInternetSales": {
				"queryName": "FactInternetSales",
				"queryGroupId": {},
				"loadEnabled": true,
				"queryId": "43556f82-75c9-4e23-962f-123e552dac05"
			}

Probable cause: the query/queries are under group "Other Queries".
Moving them to a new group "Test" solves this issue.

**Comment by nolockcz** [comment]
Thank you, Frank, for the reported bug.
I was able to reproduce your scenario and I'm going to fix it this week.

**Comment by nolockcz** [comment]
The bug has been fixed.
An annotation is ignored now if it doesn't contain any queryGroupId.
