### ISSUE TITLE
Need Reversal!

### ISSUE THREAD

**Issue by MattRudy** [nolockcz/PowerPlatform#2]
Sometimes you need to pull a complex dataflow back to a .pbix file to develop the next iteration. A second converter going the opposite way would solve this need.

**Comment by nolockcz** [comment]
Hi Matt,
unfortunately it is not possible to create a pbit file. Even when you unzip a pbit file and zip it back, Power BI Desktop refuses to open the file. There is a checksum or something similar, which prohibits making changes to a pbix or pbit file.
But if there will be a way in the future, which allows it, I'll develop the tool you request.

**Comment by MattRudy** [comment]
I have run into the checksum issue as well and have been looking for the same solution – thanks for reviewing and I’m a big fan of what you’ve built.


Matt
